### ISSUE TITLE
Make SSB the default mode when loading the Post an Activation page

### ISSUE THREAD

**Issue by magicbug** [schrockwell/hamsat_ex#30]
As for the title Make SSB the default mode when loading the Post an Activation page rather than data was its probably the more common mode.

**Comment by schrockwell** [comment]
@magicbug The default mode is whatever mode you most recently created a spot for. The idea was to try to guess your future behavior based on the past, and also to avoid having to create a preference for it. I don't agree that SSB is necessarily the best default, but I might be open to making it a user preference?

**Comment by magicbug** [comment]
Oh didn't realise that @schrockwell in that case ignore me :)
