### ISSUE TITLE
API endpoint for "personal view" on activations

### ISSUE THREAD

**Issue by phl0** [schrockwell/hamsat_ex#71]
Would it be possible to add a personalized API endpoint providing JSON data about activations which also contains info if workable? Like https://github.com/schrockwell/hamsat_ex/issues/68 but which additional info for logged in users. Maybe using an API key to provide data.

**Comment by schrockwell** [comment]
@phl0 Done! Scroll to the bottom of your [account settings page](https://hams.at/users/settings) for the URL and API key.

**Comment by phl0** [comment]
Cool. I will check it out and report.

**Comment by phl0** [comment]
It works well in my Telegram bot. It can now only announce the passes that are workable. Very fine. Thank you for your efforts.
