### ISSUE TITLE
Alert page should encourage to set a location

### ISSUE THREAD

**Issue by abrain** [schrockwell/hamsat_ex#72]
When using the site for the first time, the location is not set. The _Passes_ page asks you to set a location, however clicking on a _Track_ link results in an _Internal Server Error_.

It would be nice if this page also would gracefully handle the error and ask to set the location.

This is especially usefull when arriving at hams.at through a direct link (e.g. from Cloudlog).

**Comment by schrockwell** [comment]
> It would be nice if this page also would gracefully handle the error and ask to set the location.

It sure would! In fact, that was the behavior before. Something must have recently broke it.

Anyway, it has been fixed. Thank you for reporting it!
